# home_dir is defined in /etc/ansible/hosts for each host
exp_home: '{{ home_dir }}/knn'
dataset_dir: '{{ exp_home }}/datasets'
experiments_dir: '{{ exp_home }}/experiments'
binaries_dir: '{{ exp_home }}/bin'
les3_dir: '{{ binaries_dir }}/les3'
les3_groups: '{{ dataset_dir }}/les3'
knn_dir: '{{ exp_home }}/knn'
preprocessing_dir: '{{ exp_home }}/preprocessing'
