- name: Copy benchmark scripts
  ansible.builtin.copy:
    src: 'benchmark-runs/'
    dest: '{{ experiments_dir }}'

- name: Sync benchmark Python environment
  ansible.builtin.command:
    chdir: '{{ experiments_dir }}'
    cmd: 'uv sync'
