- name: Install build dependencies
  ansible.builtin.apt:
    pkg:
      - "build-essential"
      - "cmake"
      - "curl"
      - "git"
      - "lsb-release"
      - "man-db"
      - "ninja-build"
      - "tar"
      - "unzip"
      - "pkg-config"
      - "zip"
    state: latest

- name: Clone VCPKG
  ansible.builtin.git:
    accept_newhostkey: true
    dest: "{{ home_dir }}/.vcpkg"
    repo: "https://github.com/microsoft/vcpkg.git"
    version: master
  notify: bootstrap_vcpkg

- name: Pull knn
  ansible.builtin.git:
    repo: 'git@frosch.cosy.sbg.ac.at:dschmitt/msc-dschmitt-code.git'
    dest: '{{ knn_dir }}'
    accept_hostkey: yes
    force: yes
  notify: compile_knn

- name: Create cluster build directory
  ansible.builtin.file:
    path: '{{ knn_dir }}/build'
    state: directory
    mode: '0755'
