- include_tasks: common.yml

- name: Datasets
  include_tasks: datasets.yml
  tags: datasets

- name: Preprocessing
  include_tasks: preprocessing.yml
  tags: datasets

- name: Experiments
  include_tasks: experiments.yml
  tags: experiments

- include_tasks: knn.yml
